[package]
name = "tortoise"
version = "0.1.0"
authors = ["Raph Levien <raph.levien@gmail.com>"]
license = "MIT/Apache-2.0"
description = "An experimental SPIR-V to Rust translator"
readme = "README.md"
edition = "2018"

[dependencies]
rspirv = "0.7"
